#!/bin/sh                                                                                                                                                                                                   

dir=$1
RESULT=`ls -a $dir`
declare -a ARRAY
let count=0

for FILE in $RESULT
do
    if [ ! -L "$dir/$FILE" ]
        then
    if [ -f "$dir/$FILE" ]
        then
        ARRAY[$count]="$dir/$FILE"
        let count=count+1
#       echo "$dir/$FILE"                                                                                                                                                                                   
        fi
    fi
done

#echo "There are $count regular files."                                                                                                                                                                     

for i in "${ARRAY[@]}"
do
    for j in "${ARRAY[@]}"
    do
        #Node1 and node2 comtain the inode numbers of 2 files                                                                                                                                               
        let node1=`stat -c '%i' $i`
        let node2=`stat -c '%i' $j`
        #if the files are not identical and inode numbers are different                                                                                                                                     
        if [ $node1 != $node2 ] && [ $i != $j ]
        then
            #if the files contain the same contents                                                                                                                                                         
            if cmp -s $i $j
                then
                #Create a hard link between the files that are identical                                                                                                                                    
                rm $j
                ln $i $j

            fi
        fi


    done

done

